version: '3'
services:
  dodo-db:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_USER: 'postgres_user'
      POSTGRES_PASSWORD: 'postgres_pass'
      POSTGRES_DB: 'dodo_db'
  dodo-frontend:
    build: frontend
    volumes:
      - /dodo-frontend/tmp/
      - /dodo-frontend/node_modules/
      - ./frontend:/dodo-frontend
    ports:
      - '4202:4200'
      - '7020:7020'
      - '5779:5779'
  dodo-backend:
    build: backend
    volumes:
      - /dodo-backend/node_modules/
      - ./backend:/dodo-backend
    ports:
      - '3003:3003'
