version: '3'
services:
  dodo-db:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_USER: 'postgres_user'
      POSTGRES_PASSWORD: 'postgres_pass'
      POSTGRES_DB: 'dodo_db'
    ports:
      - '5432:5432'
  #dodo-frontend:
    #image: 'danlynn/ember-cli:3.3.0'
    #volumes: 
    #ports:
      #- '4202:4200'
      #- '7020:7020'
      #- '5779:5779'
